language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
bundler_args: --without development
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database betterbet_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

